# Generated by Django 4.2.1 on 2023-05-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID Доктора')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность:')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Докторы',
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id_human', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID Человека')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина:')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id_app', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID Записи')),
                ('app_time', models.DateField(max_length=255, verbose_name='Дата записи')),
                ('id_doctor', models.ForeignKey(on_delete=models.SET(-1), to='Medicine.doctor', verbose_name='ID Доктора')),
                ('id_human', models.ForeignKey(on_delete=models.SET(-1), to='Medicine.human', verbose_name='ID Человека')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
